/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during normal app setup and is committed here
// so a fresh clone type-checks cleanly before the first dev server run.
